### ISSUE TITLE
Mob farms are lagging server

### ISSUE THREAD

**Issue by BillyGalbreath** [BillyGalbreath/Pl3xCraft#13]
Need mob limiter and cramming rule enabled

**Comment by BillyGalbreath** [comment]
Cramming rule set to 5.

Mob limiter installed. Needs configuring.

**Comment by BillyGalbreath** [comment]
Configured. Leaving open until next weekend to verify farms dont create anymore lag

**Comment by ChrystiGalbreath** [comment]
works.. only 5 can be in a 1x1
