### ISSUE TITLE
Invisible

### ISSUE THREAD

**Issue by ChrystiGalbreath** [BillyGalbreath/Pl3xCraft#28]
When changing between /gms and /gmsp the character stays invisible

http://prntscr.com/fm94ei

**Comment by BillyGalbreath** [comment]
Elaborate this @ChrystiGalbreath

**Comment by BillyGalbreath** [comment]
After extensive testing seems this is a client bug. You only appear invisible to yourself. Other players are able to see you fine.

Mojang Bug Report: https://bugs.mojang.com/browse/MC-92324
