### ISSUE TITLE
anvil ate my books

### ISSUE THREAD

**Issue by ChrystiGalbreath** [BillyGalbreath/Pl3xCraft#31]
after pulling mending off a piece of gear the anvil dropped my gear and mending book but ate my blank books

**Comment by BillyGalbreath** [comment]
New Feature: nom nom nom

**Comment by edunlap51** [comment]
es tru. i seent it with my own eye

**Comment by ChrystiGalbreath** [comment]
Ok so after testing against a wall i had a diamond pick with mending unbreaking 3 and silk touch and 40 blank books.. took silk touch off then went to take ub3 off and anvil broke and dropped ub3 that i was taking off as well as and other ub3 and no books or pick..

after testing with anvil away from everything... it did the same thing in the open.. enchants on the pic had 40+ books went to take the silk off the anvil broke ate the pick and books and gave me 2 silk books..


so this is the 3rd and 4th incident where everytime its eating the item that is in the first slot and eating the books in the second slot then duplicating the enchant that is being removed.

I am also testing this in a claim as well as above ground so the items are not going to the top level.

**Comment by BillyGalbreath** [comment]
Fixed: https://bitbucket.org/BillyGalbreath/enchantmentsplitter/commits/92d5fe8a6fc138c72c26ece77fc1f9949d1d6d8f
