### ISSUE TITLE
clickable homes

### ISSUE THREAD

**Issue by ChrystiGalbreath** [BillyGalbreath/Pl3xCraft#34]
./homes is clickable but /home is not

**Comment by ChrystiGalbreath** [comment]
when tying /home and the list pops up you cant click the homes.. but when you do /homes and it has the yellow commas they are clickable

**Comment by BillyGalbreath** [comment]
The tab completion from the command /home is not clickable. It's not a possibility. /Homes is a list command that lists all homes in chat. Those are clickable. Chat = clickable, tab completion = not tab completable
