### ISSUE TITLE
lore on diamond sword

### ISSUE THREAD

**Issue by ChrystiGalbreath** [BillyGalbreath/Pl3xCraft#35]
lore on regular diamond sword

https://bitbucket.org/BillyGalbreath/pl3xweapons/src/201d3cd7fa28245a868a39fde8c092fda97f91b7/src/main/java/net/pl3x/bukkit/pl3xweapons/Weapon.java?at=master&fileviewer=file-view-default

**Comment by BillyGalbreath** [comment]
https://bitbucket.org/BillyGalbreath/pl3xweapons/commits/f0f5656636cd14f829f639ce687985f85bec5520
