### ISSUE TITLE
Named spawn eggs

### ISSUE THREAD

**Issue by ChrystiGalbreath** [BillyGalbreath/Pl3xCraft#39]
When spawning mobs from egg totem eggs in a claimed and unclaimed area.. Tp away then come back and mob has despawned I have only tried this with Ocelots.

**Comment by BillyGalbreath** [comment]
Test with something other than ocelots. It is a vanilla mechanic to despawn ocelots when inactive, even named ones.

https://bugs.mojang.com/browse/MC-28424

`    protected boolean isTypeNotPersistent() {
        return !this.isTamed() /*&& this.ticksLived > 2400*/; // CraftBukkit
    }`

**Comment by BillyGalbreath** [comment]
Fixed ocelots in custom server software

https://bitbucket.org/BillyGalbreath/pl3xserver/commits/4d88f11642dfcd0ee7077fa6b0246f5144f23a9c
