### ISSUE TITLE
tphere

### ISSUE THREAD

**Issue by ChrystiGalbreath** [BillyGalbreath/Pl3xCraft#4]
tphere doesnt work for mods

**Comment by BillyGalbreath** [comment]
Includes /tp and /tppos

Current state is using the vanilla /tp command  which lumps all these into a single command. Usage depends on syntax.

/tp player
/tp player1 player2
/tp x y z

Can either rewrite these commands and lose the vanilla variable syntax (@p @e etc) or can create aliases in commands.yml

**Comment by BillyGalbreath** [comment]
Not needed. Using vanilla command
