### ISSUE TITLE
nicknames

### ISSUE THREAD

**Issue by ChrystiGalbreath** [BillyGalbreath/Pl3xCraft#7]
We need nicknames for staff-- enhancement

**Comment by ChrystiGalbreath** [comment]
Its an enhancement!!

**Comment by ChrystiGalbreath** [comment]
Enhancement

**Comment by BillyGalbreath** [comment]
Will open discussions about this with staff soon.

**Comment by BillyGalbreath** [comment]
Decided not to go with this feature. Had too many issues in the past with nicknames.
